const fs            = require("fs");
const path          = require("path");
const { execSync }  = require("child_process");

// Paths
const TEMPLATE_SRC  = path.join(__dirname, "..", "..", "bnmit-typst-report-template");
const OUTPUTS_DIR   = path.join(__dirname, "..", "outputs");

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Escape a value for use inside a Typst string literal "..." */
function esc(str = "") {
  return String(str)
    .replace(/\\/g, "\\\\")
    .replace(/"/g,  '\\"');
}

/** Convert plain text to Typst content — blank lines → paragraph breaks */
function toTypst(text = "") {
  if (!text || !text.trim()) return "_No content provided._";
  return text
    .split(/\r?\n\r?\n+/)
    .map(p => p.trim().replace(/\r?\n/g, " "))
    .filter(Boolean)
    .join("\n\n");
}

/** Build Typst authors tuple: (( name: "...", usn: "..." ), ...) */
function buildAuthors(authors) {
  return authors
    .map(a => `  (\n    name: "${esc(a.name)}",\n    usn: "${esc(a.usn)}",\n  )`)
    .join(",\n");
}

/** Copy a directory recursively */
function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    entry.isDirectory() ? copyDir(s, d) : fs.copyFileSync(s, d);
  }
}

// ── Main generator ────────────────────────────────────────────────────────────
async function generateReport(doc) {
  const id      = doc._id.toString();
  const workDir = path.join(OUTPUTS_DIR, id);

  // Create fresh working directory
  if (fs.existsSync(workDir)) fs.rmSync(workDir, { recursive: true });
  fs.mkdirSync(workDir, { recursive: true });

  // ── 1. Copy entire template into workDir ─────────────────────────────────
  copyDir(TEMPLATE_SRC, workDir);

  // ── 2. Write citations.yaml ──────────────────────────────────────────────
  fs.writeFileSync(
    path.join(workDir, "citations.yaml"),
    doc.citations || ""
  );

  // ── 3. Write chapter files with real content ─────────────────────────────
  const chaptersDir = path.join(workDir, "[3] chapters");
  fs.mkdirSync(chaptersDir, { recursive: true });

  const chapters = [
    { file: "[1] Introduction.typ",               heading: "Introduction",              content: doc.introduction },
    { file: "[2] Literature Survey.typ",           heading: "Literature Survey",          content: doc.literatureSurvey },
    { file: "[3] System Requirements.typ",         heading: "System Requirements",        content: doc.systemRequirements },
    { file: "[4] Methodology & Implementation.typ",heading: "Methodology & Implementation", content: doc.methodology },
    { file: "[5] Result & Discussion.typ",         heading: "Result & Discussion",        content: doc.results },
    { file: "[6] Conclusion.typ",                  heading: "Conclusion",                 content: doc.conclusion },
  ];

  for (const ch of chapters) {
    const typst = `= ${ch.heading}\n\n${toTypst(ch.content)}\n`;
    fs.writeFileSync(path.join(chaptersDir, ch.file), typst, "utf8");
  }

  // ── 4. Generate main.typ with all data injected ──────────────────────────
  const semNum  = doc.semesterNumber || 1;
  const semWord = doc.semesterWord   || "First";

  const mainTyp = `// ====== Auto-generated by BNMIT Report Generator ======
// DO NOT EDIT MANUALLY — use the web app to regenerate

#import "template.typ": conf
#import "[1] preamble/preamble.typ": preamble
#import "[2] front-matter/front-matter.typ": front_matter
#import "[4] back-matter/back-matter.typ": back_matter

// ====== Report Details ======

#let title = "${esc(doc.title)}"

#let authors = (
${buildAuthors(doc.authors)}
)

#let guide = (
  (
    name: "${esc(doc.guide.name)}",
    designation: "${esc(doc.guide.designation)}",
    department: (
      "${esc(doc.guide.departmentAbbr)}",
      "${esc(doc.guide.departmentFull)}",
    ),
  ),
)

#let year = "${esc(doc.year)}"

#let semester = (
  ${semNum},
  "${esc(semWord)}",
)

#let department = (
  name: "${esc(doc.departmentName)}",
  abbreviation: "${esc(doc.departmentAbbr)}",
  hod: "${esc(doc.hod)}",
)

#let semester_section = "${esc(doc.section)}"

#let subject      = "${esc(doc.subject)}"
#let subject_code = "${esc(doc.subjectCode)}"

#let abstract = [
${toTypst(doc.abstract)}
]

// ====== Template ======

#show: preamble.with(
  title: title,
  subject: subject,
  subject_code: subject_code,
  authors: authors,
  guide: guide,
  semester: semester,
  section: semester_section,
  department: department,
  year: year,
)

#show: front_matter.with(
  abstract_content: abstract,
  year: year,
  department: department,
)

// ====== Chapters ======

#{
  show: conf.with(
    title: title,
    year: year,
    department: department,
  )

  include "[3] chapters/[1] Introduction.typ"
  include "[3] chapters/[2] Literature Survey.typ"
  include "[3] chapters/[3] System Requirements.typ"
  include "[3] chapters/[4] Methodology & Implementation.typ"
  include "[3] chapters/[5] Result & Discussion.typ"
  include "[3] chapters/[6] Conclusion.typ"
}

// ====== References ======

#show: back_matter()
`;

  fs.writeFileSync(path.join(workDir, "main.typ"), mainTyp, "utf8");

  // ── 5. Compile with Typst ─────────────────────────────────────────────────
  const mainFile = path.join(workDir, "main.typ");
  const pdfFile  = path.join(workDir, "report.pdf");

  try {
    execSync(`typst compile "${mainFile}" "${pdfFile}"`, {
      timeout: 120_000,
      cwd: workDir,
      stdio: "pipe",
    });
  } catch (err) {
    const stderr = err.stderr?.toString() || "";
    const stdout = err.stdout?.toString() || "";
    throw new Error(`Typst compilation failed:\n${stderr || stdout || err.message}`);
  }

  if (!fs.existsSync(pdfFile)) {
    throw new Error("Typst ran but PDF was not created.");
  }

  return pdfFile;
}

module.exports = { generateReport };
